on: [push, pull_request]
jobs:
  test:
    name: {{ '${{ matrix.name }}' }}
    runs-on: {{ '${{ matrix.os }}' }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'check'
            python: '3.9'
            tox_env: 'check'
            os: 'ubuntu-latest'
          - name: 'docs'
            python: '3.9'
            tox_env: 'docs'
            os: 'ubuntu-latest'
{% for env in tox_environments %}
{% set prefix = env.split('-')[0] -%}
{% if prefix == 'pypy3' %}
{% set python = 'pypy-3.7' %}
{% set cpython %}pp37-*{% endset %}
{% else %}
{% set python %}{{ prefix[2] }}.{{ prefix[3:] }}{% if prefix == 'py310' %}-dev{% endif %}{% endset %}
{% set cpython %}cp{{ prefix[2:] }}-*{% endset %}
{% endif %}
{% for os, python_arch, cibw_arch in [
    ['ubuntu', 'x64', 'native'],
    ['ubuntu', 'x64', 'aarch64'],
    ['windows', 'x64', 'native'],
    ['windows', 'x86', 'native'],
    ['macos', 'x64', 'native'],
] %}
{% if cibw_arch == 'native' %}
{% if python_arch == 'x64' %}
          - name: '{{ env }} ({{ os }})'
{% else %}
          - name: '{{ env }} ({{ os }}/{{ python_arch }})'
{% endif %}
{% else %}
          - name: '{{ env }} ({{ cibw_arch }})'
{% endif %}
            python: '{{ python }}'
            python_arch: '{{ python_arch }}'
            tox_env: '{{ env }}{% if 'cover' in env %},codecov{% endif %}'
            cibw_arch: '{{ cibw_arch }}'
{% if env.endswith('cover') or env.startswith('pypy') %}
            cibw_build: false
{% else %}
            cibw_build: '{{ cpython }}'
{% endif %}
            os: '{{ os }}-latest'
{% endfor %}
{% endfor %}
    steps:
    - uses: docker/setup-qemu-action@v1
      if: matrix.cibw_arch == 'aarch64'
      with:
        platforms: arm64
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: {{ '${{ matrix.python }}' }}
        architecture: {{ '${{ matrix.python_arch }}' }}
    - name: install dependencies
      run: |
        python -mpip install --progress-bar=off twine tox cibuildwheel -r ci/requirements.txt
        virtualenv --version
        pip --version
        tox --version
        pip list --format=freeze
    - name: install dependencies (gdb)
      if: >
        !matrix.cibw_build && matrix.os == 'ubuntu'
      run: >
        sudo apt-get install gdb
    - name: cibw build and test
      if: matrix.cibw_build
      run: cibuildwheel
      env:
        CIBW_ARCHS: '{{ '${{ matrix.cibw_arch }}' }}'
        CIBW_BUILD: '{{ '${{ matrix.cibw_build }}' }}'
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux1
        CIBW_BUILD_VERBOSITY: '3'
        CIBW_TEST_REQUIRES: >
          tox
          tox-direct
        CIBW_TEST_COMMAND: >
          cd {project} &&
          tox --skip-pkg-install --direct-yolo -e {{ '${{ matrix.tox_env }}' }} -v
        CIBW_TEST_COMMAND_WINDOWS: >
          cd /d {project} &&
          tox --skip-pkg-install --direct-yolo -e {{ '${{ matrix.tox_env }}' }} -v
    - name: regular build and test
      if: >
        !matrix.cibw_build
      run: >
        tox -e {{ '${{ matrix.tox_env }}' }} -v
    - name: check wheel
      if: matrix.cibw_build
      run: twine check wheelhouse/*.whl
    - name: upload wheel
      uses: actions/upload-artifact@v2
      if: matrix.cibw_build
      with:
        path: wheelhouse/*.whl
